name: release
on: [release]

jobs:
    build-remote-android:
        runs-on: windows-latest
        steps:
        - uses: actions/checkout@v1
        - uses: warrenbuckley/Setup-MSBuild@v1
        - uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '3.0.100-rc1-014190'
        - uses: actions/setup-java@v1
          with:
            java-version: '8.0.222'
        - name: restore
          run: dotnet restore src/Mobile/Mobile.Android/Mobile.Android.csproj
        - name: publish
          run: msbuild -restore src/Mobile/Mobile.Android/Mobile.Android.csproj -t:SignAndroidPackage -p:Configuration=Release -p:AndroidKeyStore=True -p:AndroidSigningKeyStore=android.keystore -p:AndroidSigningStorePass=${{ secrets.androidKeystorePassword }} -p:AndroidSigningKeyAlias=control -p:AndroidSigningKeyPass=${{ secrets.androidKeystorePassword }} -p:JavaSdkDirectory=C:\hostedtoolcache\windows\Java\8.0.222\x64
        - name: artifacts
          uses: actions/upload-artifact@master
          with:
            name: android
            path: src/Mobile/Mobile.Android/bin/Release
    
    build-target-windows:
        runs-on: windows-latest
        steps:
        - uses: actions/checkout@v1
        - uses: actions/setup-dotnet@v1
          with:
            dotnet-version: '3.0.100-rc1-014190'
        - name: restore
          run: dotnet restore src/Target/Target.csproj
        - name: publish
          run: dotnet publish -c Release -r win-x64 src/Target/Target.csproj /p:PublishTrimmed=true /p:PublishReadyToRun=true
        - name: installer
          run: |
            Invoke-WebRequest -Uri https://github.com/egramtel/nsis/raw/master/nsis.zip -OutFile build/nsis.zip
            Expand-Archive -Path build/nsis.zip -DestinationPath build
            Copy-Item build/installer.nsi -Destination src/Target/bin/Release/netcoreapp3.0/win-x64/publish
            build/makensis.exe src/Target/bin/Release/netcoreapp3.0/win-x64/publish/installer.nsi
          shell: powershell
        - name: artifacts
          uses: actions/upload-artifact@master
          with:
            name: win
            path: src/Target/bin/Release/netcoreapp3.0/win-x64/publish/control-setup.exe

    upload:
        runs-on: ubuntu-latest
        needs: [build-remote-android, build-target-windows]
        steps:
        - uses: actions/checkout@v1
        - uses: actions/download-artifact@master
          with:
            name: win
        - name: upload win installer
          uses: JasonEtco/upload-to-release@v0.1.1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          with:
            args: win/control-setup.exe application/octet-stream
        - uses: actions/download-artifact@master
          with:
            name: android
        - name: upload apk
          uses: JasonEtco/upload-to-release@v0.1.1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          with:
            args: android/com.letvalue.remotecontrol-arm64-v8a-Signed.apk application/octet-stream
        - name: upload apk
          uses: JasonEtco/upload-to-release@v0.1.1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          with:
            args: android/com.letvalue.remotecontrol-armeabi-v7a-Signed.apk application/octet-stream